# Generated by Django 3.1 on 2020-08-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
        migrations.AlterModelTable(
            name='story',
            table='Story',
        ),
    ]
