# Generated by Django 3.1 on 2020-08-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200829_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name_plural': 'Questions'},
        ),
    ]
